// AUTH
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// BICYCLES
export const FETCH_BICYCLES = "FETCH_BICYCLES";
export const FETCH_BICYCLE = "FETCH_BICYCLE";
export const CREATE_BICYCLE = "CREATE_BICYCLE";
export const UPDATE_BICYCLE = "UPDATE_BICYCLE";
export const DELETE_BICYCLE = "DELETE_BICYCLE";

// ASYNC
export const ASYNC_ACTION_START = "ASYNC_ACTION_START";
export const ASYNC_ACTION_FINISH = "ASYNC_ACTION_FINISH";
export const ASYNC_ACTION_ERROR = "ASYNC_ACTION_ERROR";

// NOTIFICATIONS
export const SNACKBAR_OPEN = "SNACKBAR_OPEN";
export const SNACKBAR_CLOSE = "SNACKBAR_CLOSE";
